### ISSUE TITLE
The WebKitGTK helper should be installed to /usr/lib instead of /usr/share

### ISSUE THREAD

**Issue by yan12125** [lantw44/ceiba-dl#4]
According to the [Filesystem Hierarchy Standard](http://www.pathname.com/fhs/pub/fhs-2.3.html) (FHS), /usr/share is for "architecture independent data files". The WebKitGTK helper, which is an ELF executable under Linux, has the same architecture as the building machine (e.g., x86_64), so it should be installed to /usr/lib instead.

**Comment by lantw44** [comment]
Yes, you are right. Platform-dependent files don't belong to 'share' and they should be put under 'lib' or 'libexec'. The reason that helper programs are installed to 'share' is that I used GNOME Shell and its 'extensions' directory as a reference when deciding places to put helper programs. It seemed to me that the easiest way was to consider helper programs as 'data' defined in XDG Base Directory Specification, which made it easy to support both system-installed and user-installed helpers. I thought it did make sense because ceiba-dl was designed to be a pure Python program with a simple WebKit-based helper to obtain cookies.

I started writing code for this project on 2017-06-03, the day when heavy rain hit Taiwan and I got 2 days off. It quickly turned out it was nearly impossible to make a WebKitGTK+ helper with pure Python because there was no API to retrieve cookies in WebKitGTK+ 2.16. The only way I found, without creating a shared library for loading into the web process, is to use `webkit_web_view_run_javascript` to retrieve the value of `document.cookie`. However, there was no GObject-introspectable JavaScriptCore API, so I could not get the result of JavaScript code in Python even if I can call `webkit_web_view_run_javascript` in Python. The first WebKitGTK+ version including GObject-introspectable API for JavaScriptCore is 2.22 released on 2018-09-03 (just 2 weeks ago!).

I did consider using Python ctypes or WebKit remote inspector. The former was hard because I didn't know how PyGObject wrapped C objects. The latter was even harder because it used a custom and undocumented D-Bus interface to communicate with the browser. Therefore, the only choice was to write the helper program in C. The WebKitGTK+ helper program was the first completed part of the project. I started working on the helper program before writing any Python code and it became the primary reason to use autotools build system in ceiba-dl.

Since WebKitGTK+ 2.20 added cookies API, and the master branch was already switched to this new API and removed all usage of JavaScriptCore API, there is no reason to write the helper program in C now. On the other hand, ceiba-dl already worked for me as a CEIBA data backup program and I no longer spent much time on it. I think there are two possible solutions to this problem:

1. Rewrite the helper in Python. It makes the original choice of using XDG Base Directory Specification to find helpers reasonable again, but it will require more work.
2. Add an exception for system-installed helpers. When we are finding system-installed helpers, search 'lib' in addition to the default XDG paths. This should be easier and less likely to introduce regressions.

What do you think? I never thought this would be packaged, but I agree it is better to follow the specification and user expectations.

**Comment by yan12125** [comment]
I'm far from a fan of rewriting programs in another language for spec-conforming issues. IMO modifying helper-finding codes is the way to go. I have another idea - as you're already using autotools to pass the path `helperdir` to Python programs, how about just relying on that and drop the XDG-based mechanism?

By the way, good writing on explaning why the helper is written in C! It's more like an inspiring blog post than a response to a GitHub issue :)

**Comment by lantw44** [comment]
> I have another idea - as you're already using autotools to pass the path `helperdir` to Python programs, how about just relying on that and drop the XDG-based mechanism?

Changing the default path of `helperdir` sounds like a good idea, but I will keep support for XDG paths. XDG paths are useful when a user wants to override the system-installed helper or expand the search path.

**Comment by yan12125** [comment]
Got it! Here you go - #5.
